version: "3.9"
name: ror-blog-stack
services:
  ror-blog:
    hostname: ror-blog 
    container_name: ror-blog
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
  
